const CACHE='ermak-b41301d1';
const FILES=["./", "index.html", "manifest.webmanifest", "icons/icon-192.png", "icons/icon-512.png", "icons/icon-180.png", "img/p-02.webp", "img/p-03.webp", "img/p-04.webp", "img/p-05.webp", "img/p-06.webp", "img/p-07.webp", "img/p-08.webp", "img/p-09.webp", "img/p-10.webp", "img/p-11.webp", "img/p-12.webp", "img/p-13.webp", "img/p-14.webp", "img/p-15.webp", "img/p-16.webp", "img/p-17.webp", "img/p-18.webp", "img/p-19.webp", "img/p-20.webp", "img/p-21.webp", "img/p-22.webp", "img/p-23.webp", "img/p-24.webp", "img/p-25.webp", "img/p-26.webp", "img/p-27.webp", "img/p-28.webp", "img/p-29.webp", "img/p-30.webp", "img/p-31.webp", "img/p-32.webp", "img/p-33.webp", "img/p-34.webp", "img/p-35.webp", "img/p-36.webp", "img/p-37.webp", "img/p-38.webp", "img/p-39.webp", "img/p-40.webp", "img/p-41.webp", "img/p-42.webp", "img/p-43.webp", "img/p-44.webp", "img/p-45.webp", "img/p-46.webp", "img/p-47.webp", "img/p-48.webp", "img/p-49.webp", "img/p-50.webp", "img/p-51.webp", "img/p-52.webp", "img/p-53.webp", "img/p-54.webp", "img/p-55.webp", "img/p-56.webp", "img/p-57.webp", "img/p-58.webp", "img/p-59.webp", "img/p-60.webp", "img/p-61.webp", "img/p-62.webp", "img/p-63.webp", "img/p-64.webp", "img/p-65.webp", "img/p-66.webp", "img/p-67.webp", "img/p-68.webp", "img/p-69.webp", "img/p-70.webp", "img/p-71.webp", "img/p-72.webp", "img/p-73.webp", "img/p-74.webp", "img/p-75.webp", "img/p-76.webp", "img/p-77.webp", "img/p-78.webp", "img/p-79.webp", "img/p-80.webp", "img/p-81.webp", "img/p-82.webp", "img/p-83.webp", "img/p-84.webp", "img/p-85.webp", "img/p-86.webp", "img/p-87.webp", "img/p-88.webp", "photo/a1_0.webp", "photo/a1_1.webp", "photo/a1_2.webp", "photo/a2_0.webp", "photo/a2_1.webp", "photo/b1_0.webp", "photo/b1_1.webp", "photo/b1_2.webp", "photo/b2_0.webp", "photo/b2_1.webp", "photo/b2_2.webp", "photo/b2_3.webp", "photo/b3_0.webp", "photo/b3_1.webp", "photo/b3_2.webp", "photo/b3_3.webp"];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const u=new URL(e.request.url);
  if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put('index.html',c));return r}).catch(()=>caches.match('index.html')));return}
  e.respondWith(caches.match(e.request,{ignoreSearch:true}).then(r=>r||fetch(e.request).then(res=>{
    if(res.ok||res.type==='opaque'){const cp=res.clone();caches.open(CACHE).then(c=>c.put(e.request,cp))}
    return res})))
});
